### ISSUE TITLE
issue connecting to Visionary-T Mini AP from Ubuntu PC

### ISSUE THREAD

**Issue by andrejpan** [SICKAG/sick_visionary_samples#14]
Any idea what is wrong here?

```bash
python -m diagnosing_devices.python.device_state_extended -i 192.168.75.235 -d'Visionary-T Mini'

***Status Overview***

Device Information:
Manufacturer: SICK AG, Firmware Version: 3.11.2.1
Device Type: Visionary-T Mini AP V3S145-1x, SDD Version: 3.11.2.2838R
Order Number: 1127086, Serial Number: 23100042

Device Status:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/andrejpa/code/sick_visionary_samples/diagnosing_devices/python/device_state_extended.py", line 137, in <module>
    runDiagnosticsDemoExtended(args.ip_address, cola_protocol, control_port)
  File "/home/andrejpa/code/sick_visionary_samples/diagnosing_devices/python/device_state_extended.py", line 37, in runDiagnosticsDemoExtended
    print("Temperature Level:", device_control.getTempLevel())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Control.py", line 917, in getTempLevel
    rx: bytes = self.readVariable(b'TmpLvl')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Control.py", line 314, in readVariable
    return self.sendCommand(b'R', name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Control.py", line 269, in sendCommand
    self.protocol.raise_cola_error(error_code)
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Protocol/ColaBase.py", line 182, in raise_cola_error
    return ColaErrors.get_error_message(error_code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Protocol/ColaErrors.py", line 109, in get_error_message
    raise RuntimeError("Cola Error: {}".format(error_message))
RuntimeError: Cola Error: unknown variable
```

```bash
ython -m visionary_welcome.python.welcome -i192.168.75.235 -d'Visionary-T Mini'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/andrejpa/code/sick_visionary_samples/visionary_welcome/python/welcome.py", line 191, in <module>
    runWelcomeDemo(args.ipAddress, cola_protocol,
  File "/home/andrejpa/code/sick_visionary_samples/visionary_welcome/python/welcome.py", line 37, in runWelcomeDemo
    device_control.stopStream()
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Control.py", line 346, in stopStream
    self.invokeMethod(b'PLAYSTOP')
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Control.py", line 328, in invokeMethod
    rx = self.sendCommand(b'M', name, data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Control.py", line 254, in sendCommand
    recvCmd, recvMode, payload = self.protocol.send(
                                 ^^^^^^^^^^^^^^^^^^^
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Protocol/Cola2.py", line 102, in send
    self.getSession(sopas_socket)
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Protocol/Cola2.py", line 84, in getSession
    cmd, mode, data = self.send(sopas_socket, b'O', b'x', payload)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Protocol/Cola2.py", line 115, in send
    request_data = self.sendToDevice(sopas_socket, msg, extra_bytes=0)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Protocol/ColaBase.py", line 130, in sendToDevice
    return ColaBase.recvResponse(sopas_socket, extra_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrejpa/code/sick_visionary_samples/base/python/Protocol/ColaBase.py", line 53, in recvResponse
    raise RuntimeError("Could not find start of framing")
RuntimeError: Could not find start of framing
```

**Comment by xfealal** [comment]
Hello @andrejpan, 

Please note that only **CX** devices are fully supported by these samples. You're device is a Visionary-T Mini **AP**, which is not supported.

Best regards.

**Comment by andrejpan** [comment]
Aha, I see. I did miss this information. 

What would be an alternative for sending and receiving from/to AP cameras?

**Comment by zimmefaSICKAG** [comment]
Hello @andrejpan,

Visionary-T Mini AP devices (V3S145-1x) are programmable devices that are part of the SICK AppSpace ecosystem. They are meant to run apps on the device itself that solve the respective application without the necessity to process the data on a host PC. These apps are either offered by SICK, e.g. via the [AppPool](https://apppool.cloud.sick.com) or a user can program his own apps using SICK AppStudio. Apps are programmed in lua. Any app management can be done via SICK AppManager.
That being said, Visionary-T Mini AP is not a streaming device. With Visionary-T Mini AP, any streaming or ethernet output needs to be programmed and defined by an app that runs on the device. This allows for a high degree of customization.
Our off-the-shelf **streaming camera offering is the Visionary-T Mini CX (V3S105-1x)**. It streams 3D and 2D data with up to 30 fps to a host PC. The samples in this repository show how to easily integrate this camera into a C++ or Python application on a host PC.
Hope this helps.

**Comment by andrejpan** [comment]
@zimmefaSICKAG Thank you for this insightful response!

I would like to follow up with a question: Do you have someone from the Visionary-T Mini AP devices team that I could communicate with? So far, our communication goes through local representatives and customer support, but things are super slow...
