### ISSUE TITLE
Failed to Connect to Visionary-T Mini via Python

### ISSUE THREAD

**Issue by shimoshida** [SICKAG/sick_visionary_samples#8]
**Environment**
- OS: ` Ubuntu 24.04 LTS`
  -   kernel: `6.8.0-31-generic`
- Python: `3.10.13`

**Problem**
I am trying to connect Visionary-T Mini via Python scripts as 
```
def main():
    device_type = "Visionary-T Mini"
    cola_protocol, control_port, _ = get_device_config(device_type)
    ip_address = "192.168.1.10"
    deviceControl = Control(ip_address, cola_protocol, control_port)
    deviceControl.open()
```

This script provides the following error
```
ERROR:root:Failed to connect to device at 192.168.1.10:2122
Traceback (most recent call last):
  File "/home/moshida/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/moshida/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/moshida/Desktop/wq-linen/python/src/main.py", line 33, in <module>
    main()
  File "/home/moshida/Desktop/wq-linen/python/src/main.py", line 29, in main
    deviceControl.open()
  File "/home/moshida/Desktop/wq-linen/python/base/python/Control.py", line 167, in open
    self.sock_sopas.connect((self.ipAddress, self.control_port))
ConnectionRefusedError: [Errno 111] Connection refused
```

IP setting toward camera looks correct
```
5: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 18:c2:bf:e9:7e:42 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.10/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::1ac2:bfff:fee9:7e42/64 scope link 
       valid_lft forever preferred_lft forever
```

Also ping works as 
```
$ ping 192.168.1.10
PING 192.168.1.10 (192.168.1.10) 56(84) bytes of data.
64 bytes from 192.168.1.10: icmp_seq=1 ttl=64 time=0.047 ms
64 bytes from 192.168.1.10: icmp_seq=2 ttl=64 time=0.083 ms
64 bytes from 192.168.1.10: icmp_seq=3 ttl=64 time=0.081 ms
^C
--- 192.168.1.10 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2064ms
rtt min/avg/max/mdev = 0.047/0.070/0.083/0.016 ms
```

Is there drivers or something I need?
Thank you so much for your help!

**Comment by xfealal** [comment]
Hello @shimoshida,

It looks like you’re attempting to connect to the device using the IP address of the network interface eth0, which differs from the IP address of your camera device. To locate the IP address of your camera, please run the following find_sensor sample:


`python3 -m finding_and_connecting_devices.python.find_sensor -i "192.168.1.10/24"`

Once you have retrieved the camera’s IP address, use it in your code.

Best regards

**Comment by shimoshida** [comment]
Thank you for your swift reply @xfealal 

> It looks like you’re attempting to connect to the device using the IP address of the network interface eth0, which differs from the IP address of your camera device. 

Since the PC and the camera are directly connected via ethernet, the network interface should be the same.
When ethernet is removed, eth0 disappears as 
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp85s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 64:4b:f0:4a:bc:7d brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.181/24 brd 192.168.3.255 scope global dynamic noprefixroute enp85s0
       valid_lft 3790sec preferred_lft 3790sec
    inet6 2400:2410:2f02:f500:da07::1006/128 scope global dynamic noprefixroute 
       valid_lft 82993sec preferred_lft 82993sec
    inet6 fe80::f015:cb1:2607:a78e/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: wwan0: <POINTOPOINT,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/none 
6: wlp0s20f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 74:13:ea:a2:83:98 brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.138/24 brd 192.168.3.255 scope global dynamic noprefixroute wlp0s20f3
       valid_lft 3793sec preferred_lft 3793sec
    inet6 2400:2410:2f02:f500:da07::1005/128 scope global dynamic noprefixroute 
       valid_lft 82995sec preferred_lft 82995sec
    inet6 fe80::244:f28e:a9f1:e463/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

When ethernet is connected, eth0 appears
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp85s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 64:4b:f0:4a:bc:7d brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.181/24 brd 192.168.3.255 scope global dynamic noprefixroute enp85s0
       valid_lft 3606sec preferred_lft 3606sec
    inet6 2400:2410:2f02:f500:da07::1006/128 scope global dynamic noprefixroute 
       valid_lft 82809sec preferred_lft 82809sec
    inet6 fe80::f015:cb1:2607:a78e/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: wwan0: <POINTOPOINT,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/none 
6: wlp0s20f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 74:13:ea:a2:83:98 brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.138/24 brd 192.168.3.255 scope global dynamic noprefixroute wlp0s20f3
       valid_lft 3608sec preferred_lft 3608sec
    inet6 2400:2410:2f02:f500:da07::1005/128 scope global dynamic noprefixroute 
       valid_lft 82811sec preferred_lft 82811sec
    inet6 fe80::244:f28e:a9f1:e463/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
7: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 18:c2:bf:e9:7e:42 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.10/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::1ac2:bfff:fee9:7e42/64 scope link 
       valid_lft forever preferred_lft forever
```


>To locate the IP address of your camera, please run the following find_sensor sample:
>
>python3 -m finding_and_connecting_devices.python.find_sensor -i "192.168.1.10/24"
>
>Once you have retrieved the camera’s IP address, use it in your code.

I have tried to run the sample script, but it says 0 devices
> $ python -m  finding_and_connecting_devices.python.find_sensor -i "192.168.1.10/24"
> Number of found devices:  0

Is the network setup wrong in the first place?

**Comment by xfealal** [comment]
It looks like the script isn’t working because the default IP address of the camera is set to 192.168.1.10, which conflicts with the current IP address of your eth0 interface (also 192.168.1.10).

You can either change the IP address of your network interface or change the camera device IP address via `SopasET`. 

If you've access to `SopasET`, it might be the easier to change the devices IP address directly. 

Otherwise to resolve this, you can change the IP address of your eth0 interface for example to 192.168.1.100. 

```
sudo ip addr add 192.168.1.100/24 dev eth0
sudo ip link set dev eth0 up
```
Verify the change by running:
```
ip addr show eth0
```

After making this change, try running the find_sensor script again:
```
python -m finding_and_connecting_devices.python.find_sensor -i "192.168.1.100/24"
```
You should see that the camera has the default IP `192.168.1.10`. 

To change the IP address of the device you can run the `configure_sensor` script.

**Comment by shimoshida** [comment]
@xfealal I tried to do as you taught me, but it did not work.
```
$ sudo ip link set dev eth0 up
$ ip addr show eth0
8: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 18:c2:bf:e9:7e:42 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.100/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::1ac2:bfff:fee9:7e42/64 scope link 
       valid_lft forever preferred_lft forever
$ python -m finding_and_connecting_devices.python.find_sensor -i "192.168.1.100/24"
Number of found devices:  0
```

> If you've access to SopasET, it might be the easier to change the devices IP address directly.

Can I use the SopasET via Ubuntu ?

**Comment by xfealal** [comment]
`NO-CARRIER and state DOWN` indicate that no physical link could be established.
Is the network cable correctly plugged in? Does the cable work properly? Can you test with a different cable?
Last but not least try power-cycling (Off->On) the device.

**Comment by shimoshida** [comment]
I changed my computer to Desktop and got it working as you showed me... 
I had Ubuntu on my laptop, so I had multiple Network Interfaces, and it might have been sending to different places...

Thank you very much for your generous support. @xfealal

**Comment by xfealal** [comment]
Glad to hear that you managed to resolve the issue. 
Best regards
