### ISSUE TITLE
Unable to Communicate Stably with Visionary-T Mini via Python

### ISSUE THREAD

**Issue by shimoshida** [SICKAG/sick_visionary_samples#9]
**Environment**
- OS: ` Ubuntu 20.04 LTS`
  -   kernel: `5.15.0-122-generic`
- Python: `3.10.11`

**Problem**
Sorry for the continuous inquiries.
I have tried to run modified `continuous_streaming.py` (just delete lines relevant to pointcloud)
https://github.com/SICKAG/sick_visionary_samples/blob/main/image_streaming_and_storing/python/continuous_streaming.py

Sometimes it works if you run it a few times, sometimes it doesn't.
In the cases, the script provides timeout error
```
# pattern 1
Traceback (most recent call last):
  File "/home/moshida/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/moshida/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/moshida/Desktop/sick_visionary_samples/image_streaming_and_storing/python/camera.py", line 209, in <module>
    runContinuousStreamingDemo(args.ipAddress, args.transport_protocol, args.receiver_ip,
  File "/home/moshida/Desktop/sick_visionary_samples/image_streaming_and_storing/python/camera.py", line 114, in runContinuousStreamingDemo
    streaming_device.getFrame()
  File "/home/moshida/Desktop/sick_visionary_samples/base/python/Stream.py", line 158, in getFrame
    raise socket.timeout("BLOB header received a timeout")
TimeoutError: BLOB header received a timeout

# pattern 2
Traceback (most recent call last):
  File "/home/moshida/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/moshida/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/moshida/Desktop/sick_visionary_samples/image_streaming_and_storing/python/camera.py", line 209, in <module>
    runContinuousStreamingDemo(args.ipAddress, args.transport_protocol, args.receiver_ip,
  File "/home/moshida/Desktop/sick_visionary_samples/image_streaming_and_storing/python/camera.py", line 68, in runContinuousStreamingDemo
    device_control.open()
  File "/home/moshida/Desktop/sick_visionary_samples/base/python/Control.py", line 167, in open
    self.sock_sopas.connect((self.ipAddress, self.control_port))
TimeoutError: timed out
```

Can this be resolved somehow?
My camera is getting very hot, could it be due to heat?

**Comment by xfealal** [comment]
Hello @shimoshida, 
do you get the same unstable behaviour running the unmodified samples?

**Comment by shimoshida** [comment]
@xfealal 
Yes, TimeoutError occurs... Is the cable unstable?
```
$python -m image_streaming_and_storing.python.continuous_streaming -i 192.168.1.10
Data Timestamp [YYYY-MM-DD HH:MM:SS.mm] = 2020-01-01 00:00:16.946
Data contains depth map data:
=== Write PNG file: Frame number: 114
=== Converting image to pointcloud
convertToPointCloud took: 0.948s
convertToPointCloudOptimized took: 0.0339s
Traceback (most recent call last):
  File "/home/moshida/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/moshida/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/moshida/Desktop/sick_visionary_samples/image_streaming_and_storing/python/continuous_streaming.py", line 232, in <module>
    runContinuousStreamingDemo(args.ipAddress, args.transport_protocol, args.receiver_ip,
  File "/home/moshida/Desktop/sick_visionary_samples/image_streaming_and_storing/python/continuous_streaming.py", line 116, in runContinuousStreamingDemo
    streaming_device.getFrame()
  File "/home/moshida/Desktop/sick_visionary_samples/base/python/Stream.py", line 194, in getFrame
    nBytes = self.sock_stream.recv_into(view, toread)
TimeoutError: timed out
```

**Comment by shimoshida** [comment]
If you are monitoring the camera all the time, it is possible that the camera stops in the middle of the session. Is this something bad around the power supply...?
![stop-camera](https://github.com/user-attachments/assets/e310b35a-a522-4d93-8aac-87fb6a268ab8)

**Comment by xfealal** [comment]
Hello @shimoshida, 
The camera getting hot is expected behaviour. You can place the camera on top of an aluminium plate which helps cooling the device. 
It seems your camera goes unexpectedly into reboot. Can you tell us which `firmware version` you're running on the device? 
You can use the [device_state_extended sample](https://github.com/SICKAG/sick_visionary_samples/blob/main/diagnosing_devices/python/device_state_extended.py) to get the Firmware version or SopasET.

**Comment by xfealal** [comment]
Thank you for providing the complete diagnostic report. It appears that the issue lies with the operating voltage being supplied to the device. The minimum required voltage is 16.8V, whereas the current supply is approximately 12.8V.

Please ensure that the device consistently receives a **minimum voltage of 16.8V.**

***Status Overview***

...
**OpVoltageStatus: ERROR**
...

Operating Voltage:
**Current Operating Voltage: 12.81 V**
Minimal Voltage (since start): 12.81 V
Maximal Voltage (since start): 15.38 V
The required operating voltage is between: **16.80 V** and 30.00 V

**Comment by shimoshida** [comment]
@xfealal As you pointed out, I changed the power supply and now it runs stable.
I apologize for asking you twice about something that has nothing to do with the library. 
Thank you very much for your generous support again.

```
$ python -m diagnosing_devices.python.device_state_extended -i 192.168.1.10

***Status Overview***

Device Information:
Manufacturer: SICK AG, Firmware Version: 3.11.2.1
Device Type: Visionary-T Mini CX V3S105-1x, SDD Version: 2.1.0.3341R
Order Number: 1112649, Serial Number: 24210035

Device Status:
Temperature Level: GOOD
Illumination Active: True
OpVoltageStatus: GOOD
Digital IO Status: True
Image Acquisition (Frontend Mode): CONTINUOUS

Service Information:
Power On Count: 4922
Operating Hours: 10:48 hh:mm
Up Time: 00:08 hh:mm

Operating Voltage:
Current Operating Voltage: 24.02 V
Minimal Voltage (since start): 22.98 V
Maximal Voltage (since start): 24.11 V
The required operating voltage is between: 16.80 V and 30.00 V

Temperatures:
Current System Temperature: 37.00°C
Illumination: 46.0°C
ProcessorAmbient: 40.6°C
FpgaCore: 47.1°C
ImagerBoard: 45.7°C
CPU: 47.0°C

Digital In- and Output:
Thermal Overload: False
Out1 short ciruit error: False
Out2 short ciruit error: False
Out3 short ciruit error: False
Out4 short ciruit error: False
Out5 short ciruit error: False
Out6 short ciruit error: False
Out7 short ciruit error: False
Out8 short ciruit error: False

Ethernet statistics
Ethernet speed TX_AUTO

Error Log:
First Time           | Last Time            | Description                                        | Info                           | State      | Occurrences  | ID   
---------------------------------------------------------------------------------------------------------------------------------------------------
10:39:5              | 10:39:5              | No ethernet cable                                  |                                | INACTIVE   | 1            | 33558276
10:47:59             | 10:47:59             | Connection closed by peer                          | eth0:TCP:2114:192.168.1.100 in TX code 104 | INACTIVE   | 1            | 33558278
```

**Comment by xfealal** [comment]
Nice to hear that the device and the samples run stable.
No worries @shimoshida, sometimes the exact issue canno't be known at first glance. 
Feel free to ask. We're here to help.
